"""
Name: Madeline Boss, Mahi Agrawal
Date: 10/27/25
Assignment: 4
Due Date: November 4, 2025
About this project: The goal of this project is to create a functional internet chat server using our knowledge of socket programming and 
networking.
Assumptions: 
All work below was performed solely by Madeline Boss and Mahi Agrawal.
I did not use code generated by an AI tool.
"""