"""
Name: Madeline Boss
Date: September 20, 2025
Assignment: 2
Due Date: September 26, 2025
About this project: This program analyzes Apache web server access logs and reports
the most active hosts and most frequently downloaded resources in a given date range.
Assumptions: Input log file is in the Combined Log Format.
All work below was performed solely by Madeline Boss.
I did not use code generated by an AI tool.
"""